special_tokens:
  - "<|endoftext|>"
enable_log: False
log_path: "gold.log"
serialization: True
serialization_vocab_path: "serialization_vocab.json"
serialization_merge_path: "serialization_merge.json"
traindata_path: "training_data.txt"
vocab_size: 500
gpt2_regex: True
parallel: True