special_tokens:
  - "<|endoftext|>"
enable_log: False
log_path: "cs336_basics/outputs/gold.log"
serialization: True
serialization_vocab_path: "cs336_basics/outputs/serialization_vocab.json"
serialization_merge_path: "cs336_basics/outputs/serialization_merge.json"
traindata_path: "cs336_basics/training_corpus.txt"
vocab_size: 500
gpt2_regex: True
parallel: True
