special_tokens:
  - "<|endoftext|>"
enable_log: False
log_path: "/Users/lucas/Documents/GitHub/stf-assignment1-basics/cs336_basics/gold.log"
serialization: True
serialization_vocab_path: "/Users/lucas/Documents/GitHub/stf-assignment1-basics/cs336_basics/serialization_vocab.json"
serialization_merge_path: "/Users/lucas/Documents/GitHub/stf-assignment1-basics/cs336_basics/serialization_merge.json"
traindata_path: "/Users/lucas/Documents/GitHub/stf-assignment1-basics/cs336_basics/training_data.txt"
vocab_size: 500
gpt2_regex: True
parallel: True