version: "3.9"

services:
  bpe:
    image: cs336-bpe:prod-1.0.0
    build:
      context: .
      tags: ["cs336-bpe:prod-1.0.0"]   # builds only if image missing or you run with --build
    working_dir: /app
    volumes:
      # - ./:/app                 # bind-mount code for fast iteration
      - /Users/lucas/Downloads/temp_sft/data:/data:ro
    env_file:
      - .env       # env file location
    command: ["./start_zhl.sh"]
    # healthcheck:
    #   test: ["CMD-SHELL", "test -f /app/cs336_basics/outputs/health.ok || exit 1"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 30s         # optional: give the job a moment to start


    
